### ISSUE TITLE
Test Fails on Windows

### ISSUE THREAD

**Issue by otariidae** [shuhei/material-colors#17]
OS: Windows7  
Node: v7.4.0  
Error Message:
```
[...]
Error: Command failed: (my directory)\material-colors\node_modules\.bin\rollup -f es (my directory)\material-colors\test\fixtures\default-import.js | (my node dirctory)\node.exe
[...]
    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at (my dirctory)\material-colors\test\module.js:18:16
    at Array.forEach (native)
    at Object.<anonymous> ((my dirctory)\material-colors\test\module.js:9:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Test failed.  See above for more details
```
Windows does not understand `|` command, which seems why test fails.  
It may be good to use [rollup JavaScript API](https://github.com/rollup/rollup/wiki/JavaScript-API) instead of `child_process.execSync` and `console.log`.

**Comment by shuhei** [comment]
Thanks for reporting. It seems a good idea to use JS API.

**Comment by shuhei** [comment]
Made [a change](https://github.com/shuhei/material-colors/commit/204d7e9210ded88054766c9737b3c0738038c2e5) to use rollup JavaScript API and tmp file to remove `|`. Does it work for you?

**Comment by otariidae** [comment]
Thank you!  
But I have other problems.
- Spaces in path causes an error in `execSync`.
   e.g. 'Program Files'
- Line break is not equal to `os.EOL` on my PC.
